### ISSUE TITLE
Schema in Table Name Causing error

### ISSUE THREAD

**Issue by DureSameen** [AlenToma/EntityWorker.Core#3]
[Table("Sales.CustomerTransactions")]

This table name is  generating error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Ungültiger Objektname "Sales.CustomerTransactions".
   at EntityWorker.Core.Transaction.Transaction.DataReaderConverter(DbCommandExtended command, Type type)
   at EntityWorker.Core.Transaction.Transaction.DataReaderConverter[T](DbCommandExtended command)
   at EntityWorker.Core.DbSchema.Select[T](String query)
   at EntityWorker.Core.Transaction.Transaction.Select[T](String sqlString)
   at EntityWorker.Core.Object.Library.SqlQueryable`1.Execute()
   at Performance.EWRepository.GetAllCustomersTransactions(Int32 CustomerId) in D:\TIKOS\Performance\Performance\EWRepository.cs:line 15
   at Performance.EWCoreVsDapper.GetCustomersTransactionsWithEntityWorker() in D:\TIKOS\Performance\Performance\EWCoreVsDapper.cs:line 24
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
   at BenchmarkDotNet.Engines.Engine.Jitting()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args)

**Comment by AlenToma** [comment]
I just published new package and added a safeguard for invalid property names and table names.
all none character and none numeric will be repleaced with `_ `
This is the best solution right now becouse i have some providers that do not accept character like you provided.
so Sales.CustomerTransactions will be repleaced to Sales_CustomerTransactions
this is the reexp that i added `[^a-zA-Z0-9,_]`

**Comment by DureSameen** [comment]
Thanks for prompt action.
